import type { DashboardState } from '@exitos/core/schema';
import { memo, useMemo, type ReactNode } from 'react';
import { Header } from './components/Header';
import { EmptyState, ErrorScreen, LoadingScreen, StaleBanner } from './components/Screens';
import { LiveContext, type RecordingWording } from './hooks/LiveContext';
import { useDashboardState, type DashboardStore } from './hooks/useDashboardState';
import { Compatibility } from './sections/Compatibility';
import { MappingPreview } from './sections/MappingPreview';
import { Overview } from './sections/Overview';
import { Progress } from './sections/Progress';
import { SourceDestination } from './sections/SourceDestination';
import { Unsupported } from './sections/Unsupported';
import { VerificationReport } from './sections/Verification';

/** Re-renders only when the state document actually changed (not on every poll). */
const Sections = memo(function Sections({ state }: { state: DashboardState }) {
  const plan = state.plan;
  if (plan === null) return <EmptyState state={state} />;
  return (
    <div className="space-y-10 sm:space-y-14">
      <Overview state={state} plan={plan} />
      <SourceDestination state={state} plan={plan} />
      <Compatibility plan={plan} />
      <MappingPreview plan={plan} />
      <Unsupported state={state} plan={plan} />
      <Progress state={state} plan={plan} />
      <VerificationReport state={state} plan={plan} />
    </div>
  );
});

/**
 * What the static online demo adds around the dashboard. It is `undefined` for the normal local
 * dashboard, which therefore renders exactly as before.
 */
export interface DemoFrame {
  /** The badge in the header (replaces the mode badge) and the words after "ExitOS" there. */
  badge: ReactNode;
  subtitle: string;
  /** Shown instead of the local-server loading and error screens. */
  loading: ReactNode;
  error: (message: string, onRetry: () => void, busy: boolean) => ReactNode;
  /** How the Progress section talks about a recording. */
  recording: RecordingWording;
  /** Above the sections: the DEMO notice and the guided tour. Shown while loading, too. */
  before: ReactNode;
  /** Below the sections: the "Run it for real" panel. Shown once there is data. */
  after: ReactNode;
  /** Replaces the footer text. */
  footer: ReactNode;
}

/** The dashboard page for any source of state: the local server, or the online demo's recording. */
export function DashboardView({ store, demo }: { store: DashboardStore; demo?: DemoFrame }) {
  const { state, status, error } = store;
  const recording = demo?.recording;
  const live = useMemo(
    () => ({
      lastUpdated: store.lastUpdated,
      refreshing: store.refreshing,
      pollMs: store.pollMs,
      refresh: store.refresh,
      recording,
    }),
    [store.lastUpdated, store.refreshing, store.pollMs, store.refresh, recording],
  );
  const showData = state !== null && state.plan !== null && state.mode !== 'empty';
  const failed = status === 'error' || (state === null && error !== null);

  return (
    <>
      <a href="#main" className="skip-link">
        Skip to content
      </a>
      <Header
        mode={state ? state.mode : status === 'error' ? 'error' : 'loading'}
        showNav={showData}
        badge={demo?.badge}
        {...(demo ? { subtitle: demo.subtitle } : {})}
      />
      <main id="main" className="mx-auto max-w-7xl px-4 py-5 sm:px-6 sm:py-8" tabIndex={-1}>
        {demo?.before}
        {status === 'loading' ? demo ? demo.loading : <LoadingScreen /> : null}
        {failed ? (
          demo ? (
            demo.error(error ?? 'Unknown error.', store.refresh, store.refreshing)
          ) : (
            <ErrorScreen
              message={error ?? 'Unknown error.'}
              onRetry={store.refresh}
              busy={store.refreshing}
            />
          )
        ) : null}
        {state !== null ? (
          <>
            {error !== null ? (
              <StaleBanner message={error} onRetry={store.refresh} busy={store.refreshing} />
            ) : null}
            {state.mode === 'empty' ? (
              <EmptyState state={state} />
            ) : (
              <LiveContext.Provider value={live}>
                <Sections state={state} />
              </LiveContext.Provider>
            )}
            {demo?.after}
          </>
        ) : null}
        <footer className="mt-12 border-t border-line pt-4 text-sm text-muted">
          {demo ? (
            demo.footer
          ) : (
            <>
              ExitOS dashboard · read-only · served by <code>exitos ui</code> on this computer. It
              shows only what is in the local state; it never contacts Notion or ClickUp.
              {state ? <> Generated by ExitOS {state.exitosVersion}.</> : null}
            </>
          )}
        </footer>
      </main>
    </>
  );
}

export function App() {
  return <DashboardView store={useDashboardState()} />;
}
