import type { DashboardState } from '@exitos/core/schema';
import { memo, useMemo } from 'react';
import { Header } from './components/Header';
import { EmptyState, ErrorScreen, LoadingScreen, StaleBanner } from './components/Screens';
import { LiveContext } from './hooks/LiveContext';
import { useDashboardState } from './hooks/useDashboardState';
import { Compatibility } from './sections/Compatibility';
import { MappingPreview } from './sections/MappingPreview';
import { Overview } from './sections/Overview';
import { Progress } from './sections/Progress';
import { SourceDestination } from './sections/SourceDestination';
import { Unsupported } from './sections/Unsupported';
import { VerificationReport } from './sections/Verification';

/** Re-renders only when the state document actually changed (not on every poll). */
const Sections = memo(function Sections({ state }: { state: DashboardState }) {
  const plan = state.plan;
  if (plan === null) return <EmptyState state={state} />;
  return (
    <div className="space-y-12">
      <Overview state={state} plan={plan} />
      <SourceDestination state={state} plan={plan} />
      <Compatibility plan={plan} />
      <MappingPreview plan={plan} />
      <Unsupported state={state} plan={plan} />
      <Progress state={state} plan={plan} />
      <VerificationReport state={state} plan={plan} />
    </div>
  );
});

export function App() {
  const store = useDashboardState();
  const { state, status, error } = store;
  const live = useMemo(
    () => ({
      lastUpdated: store.lastUpdated,
      refreshing: store.refreshing,
      pollMs: store.pollMs,
      refresh: store.refresh,
    }),
    [store.lastUpdated, store.refreshing, store.pollMs, store.refresh],
  );
  const showData = state !== null && state.plan !== null && state.mode !== 'empty';

  return (
    <>
      <a href="#main" className="skip-link">
        Skip to content
      </a>
      <Header
        mode={state ? state.mode : status === 'error' ? 'error' : 'loading'}
        showNav={showData}
      />
      <main id="main" className="mx-auto max-w-7xl px-4 py-6 sm:px-6" tabIndex={-1}>
        {status === 'loading' ? <LoadingScreen /> : null}
        {status === 'error' || (state === null && error !== null) ? (
          <ErrorScreen
            message={error ?? 'Unknown error.'}
            onRetry={store.refresh}
            busy={store.refreshing}
          />
        ) : null}
        {state !== null ? (
          <>
            {error !== null ? (
              <StaleBanner message={error} onRetry={store.refresh} busy={store.refreshing} />
            ) : null}
            {state.mode === 'empty' ? (
              <EmptyState state={state} />
            ) : (
              <LiveContext.Provider value={live}>
                <Sections state={state} />
              </LiveContext.Provider>
            )}
          </>
        ) : null}
        <footer className="mt-12 border-t border-line pt-4 text-sm text-muted">
          ExitOS dashboard · read-only · served by <code>exitos ui</code> on this computer. It shows
          only what is in the local state; it never contacts Notion or ClickUp.
          {state ? <> Generated by ExitOS {state.exitosVersion}.</> : null}
        </footer>
      </main>
    </>
  );
}
